name: musicapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # پکیج‌های اصلی
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  google_fonts: ^6.1.0
  provider: ^6.0.5

  # پکیج‌های صوتی
  just_audio: ^0.10.3
  audio_video_progress_bar: ^2.0.3
  audio_service: ^0.18.5

  # پکیج‌های جانبی
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.3.0
  lottie: ^3.1.0
  flutter_animate: ^4.3.0
  image_picker: ^1.0.7

  # پکیج‌های اضافه‌شده
  animated_button: ^0.2.0
  google_sign_in: ^6.2.1
  flutter_animated_button: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  #  fonts:
#    - family: iransans
#      fonts:
#        - asset: assets/fonts/IranianSans.ttf
